# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
#orbs:
  # Declare a dependency on the welcome-orb
  # slack: circleci/slack@0.1.0
  
jobs:
  deploy:
    docker:
      - image: "navikt/deployment-cli:v0.1.2"
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - fpabakus-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - fpabakus-dependencies-
      - run: mvn -DskipTests clean install dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: fpabakus-dependencies-{{ checksum "pom.xml" }}     
      - run:
          name: Build docker image
          command: docker build -t navikt/abakus:${CIRCLE_SHA1} .
      - run:
          name: Release docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push navikt/abakus:${CIRCLE_SHA1}
      - run: # Username and password is set through $DEPLOYMENT_USERNAME and $DEPLOYMENT_PASSWORD
          name: Create deployment request for development
          command: deployment-cli deploy create --environment=dev-fss --repository=navikt/abakus --team=foreldrepenger -r=naiserator.yaml --version=${CIRCLE_SHA1}
      #- run: # Username and password is set through $DEPLOYMENT_USERNAME and $DEPLOYMENT_PASSWORD
       #   name: Create deployment request for prod
        #  command: deployment-cli deploy create --environment=prod-fss --repository=navikt/abakus --team=foreldrepenger -r=naiserator.yaml --version=${CIRCLE_SHA1}
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      

