name: Trigger verdikjedetest

on: [registry_package]

jobs:
  verdikjedetriggere:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger verdikjedetester K9
        if: ${{ github.event.client_payload.github.payload.action }} == "published" && ${{ github.event.client_payload.github.payload.package.package_type }} == "docker" && ${{ github.event.client_payload.github.payload.package.package_version.version }} != "latest"
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          repository: navikt/k9-verdikjede
          event-type: saksbehandling-verdikjede
          client-payload: '{ "trigger": "${{ github.repository }}", "version": "${{ env.TAG }}", "image": "${{ env.IMAGE }}"}'
